<?php
/**
 * Created by PhpStorm.
 * User: Rus
 * Date: 31.01.2018
 * Time: 14:25
 */

namespace frontend\components;
use app\models\Knowledge;
use yii\base\Widget;
use yii\bootstrap\Nav;

class NavKnowledge extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $titleArr = [];
//        $name = ArrayHelper::map(Knowledge::find()->all(), 'id', 'title');
        foreach (Knowledge::find()->all() as $key => $value) {
            array_push($titleArr, ['label' => $value->title, 'url' => (['site/post', 'id' => $value->id])]);
        }
//        echo '<ul class="nav nav-pills nav-stacked">'.
//            foreach ($name as $key => $value){
//                echo '<li>'. Html::a($value, ['site/post', 'id' => $key]).'</li>';
//            }.'
//        </ul>';
        return Nav::widget([
            'options' => ['class' => 'nav nav-pills nav-stacked'],
            'items' => $titleArr
        ]);
    }
}