<?php
/**
 * Created by PhpStorm.
 * User: Rus
 * Date: 31.01.2018
 * Time: 14:25
 */

namespace frontend\components;
use app\models\Knowledge;
use yii\base\Widget;
use yii\bootstrap\Nav;

class NavKnowledge extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $titleArr = [];
        foreach (Knowledge::find()->all() as $key => $value) {
            $titleArr[] = ['label' => $value->title, 'url' => (['site/post', 'id' => $value->id])];
        }
        return Nav::widget([
            'options' => ['class' => 'nav nav-pills nav-stacked'],
            'items' => $titleArr
        ]);
    }
}