<?php

namespace frontend\components;

use app\models\Thema;
use yii\base\Widget;
use yii\bootstrap\Nav;

class NavThema extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::init();
        $themaArr = [];
        foreach (Thema::find()->all() as $thema){
            $themaArr[] = ['label' => $thema->name, 'url' => ['#']];
        }

        return Nav::widget([
            'options' => ['class' => 'nav nav-pills nav-stacked'],
            'items' => $themaArr
        ]);
    }
}